[package]
name = "htmb"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
insta = { version = "1.39.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[[bench]]
name = "basic"
harness = false
