name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  test-build-lint:
    name: Test, build & lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - run: cargo test --features pretty-print

      - run: cargo test --features pretty-print,unstable-builder

      - run: cargo build --release

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
